#!/usr/bin/env python3
"""Synthesis reports.

    python3 tools/synth_report.py [--check]   resources -> synth/report.md
    python3 tools/synth_report.py --timing    delays    -> synth/timing.md

The first reads the Yosys `stat -json` output of the three builds (core A,
core B, core B with the FPU: build/synth/{single,pipe,pipe_fd}/
utilization.json); --check exits non-zero if one of them does not fit the
XC7S50.  The second reads the logic-only static timing of `make sta`
(build/synth/{single,pipe,pipe_fd}/sta.txt)."""

import json
import re
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
# Spartan-7 XC7S50 (Xilinx DS180): 32,600 LUTs, 65,200 flip-flops,
# 75 x 36 Kb block RAM, 120 DSP48E1 slices.
CAPACITY = {"LUT": 32600, "FF": 65200, "BRAM36": 75, "DSP": 120}
LUTRAM_LUTS = {"RAM32M": 4, "RAM64M": 4, "RAM32X1D": 2, "RAM64X1D": 2, "RAM128X1D": 4, "RAM32X1S": 1,
               "RAM64X1S": 1, "RAM128X1S": 2, "RAM256X1S": 4}
NAMES = {
    "core_single": "core A (everything below)", "core_pipe": "core B (everything below)",
    "csr_file": "CSRs and 12 x 64-bit counters", "muldiv_comb": "combinational multiplier + divider",
    "divider": "iterative divider", "dcache": "D-cache (2 x 2 KiB, write-back)", "icache": "I-cache (4 KiB)",
    "bpred": "branch predictor (BTB 128, BHT 256, RAS 8)", "regfile": "register file",
    "alu": "ALU", "decoder": "decoder", "lsu_align": "load/store alignment", "mem_arbiter": "bus arbiter",
    "fpu": "FPU (everything in the FPU rows below)", "fp_fma": "FPU: multiply-add datapath",
    "fp_divsqrt": "FPU: divide / square root", "fp_round": "FPU: rounder", "fp_f2i": "FPU: float to integer",
    "fp_misc": "FPU: one-cycle operations", "fp_unpack": "FPU: unpack (one of three)",
    "fp_regfile": "f register file (32 x 64, three read ports)", "fp_decoder": "F/D decoder",
}


def base(name):
    name = name.lstrip("\\")
    m = re.match(r"^\$paramod\$?[0-9a-f]*\\?([A-Za-z_0-9]+)", name)
    return m.group(1) if m else name


def resolve(mods, t):
    for k in (t, "\\" + t):
        if k in mods:
            return k
    return None


def totals(mods, name, memo):
    if name in memo:
        return memo[name]
    c = Counter()
    for t, n in mods[name]["num_cells_by_type"].items():
        sub = resolve(mods, t)
        if sub:
            for k, v in totals(mods, sub, memo).items():
                c[k] += n * v
        else:
            c[t] += n
    memo[name] = c
    return c


def classify(c):
    logic = sum(v for k, v in c.items() if re.fullmatch(r"LUT[1-6]|INV", k))
    lutram = sum(v * LUTRAM_LUTS.get(k, 0) for k, v in c.items())
    return {"LUT": logic + lutram, "LUTRAM": lutram,
            "FF": sum(v for k, v in c.items() if re.fullmatch(r"FD[A-Z]*", k)),
            "BRAM36": c["RAMB36E1"] + c["RAMB18E1"] / 2, "DSP": c["DSP48E1"], "CARRY4": c["CARRY4"],
            "RAMB36E1": c["RAMB36E1"], "RAMB18E1": c["RAMB18E1"]}


def fmt(v):
    return f"{v:g}" if isinstance(v, float) else f"{v:,}"


def section(core, title):
    d = json.loads((REPO / "build" / "synth" / core / "utilization.json").read_text())
    mods = d["modules"]
    memo = {}
    top = resolve(mods, f"top_{core}")
    total = classify(totals(mods, top, memo))
    out = [f"## {title}", "", "| Resource | Used | XC7S50 | Share |", "|---|---:|---:|---:|"]
    labels = {"LUT": "LUTs (logic + LUTRAM)", "FF": "Flip-flops", "BRAM36": "Block RAM (36 Kb units)",
              "DSP": "DSP48E1"}
    for k in ("LUT", "FF", "BRAM36", "DSP"):
        out.append(f"| {labels[k]} | {fmt(total[k])} | {fmt(CAPACITY[k])} | {100 * total[k] / CAPACITY[k]:.1f}% |")
    out += ["", f"Also: {total['CARRY4']:,} CARRY4, {total['LUTRAM']:,} LUTs used as distributed RAM, "
                f"block RAM = {total['RAMB36E1']} RAMB36E1 + {total['RAMB18E1']} RAMB18E1.", ""]
    rows = []
    for m in mods:
        b = base(m)
        if b in NAMES and not b.startswith("top_"):
            own = classify(totals(mods, m, memo))
            rows.append((b, own))
    if rows:
        out += ["| Block (including its sub-blocks) | LUT | FF | BRAM36 | DSP |", "|---|---:|---:|---:|---:|"]
        for b, own in sorted(rows, key=lambda r: -r[1]["LUT"]):
            out.append(f"| {NAMES[b]} | {fmt(own['LUT'])} | {fmt(own['FF'])} | {fmt(own['BRAM36'])} | {fmt(own['DSP'])} |")
        out.append("")
    fits = all(total[k] <= CAPACITY[k] for k in CAPACITY)
    return out, fits, total


def timing():
    out = ["# Logic-only timing estimate (Yosys `sta`)", "",
           "Generated by `make sta`. Yosys' static timing pass over the cell delay models of its "
           "Xilinx 7-series library, after `synth_xilinx -flatten -nolutram` (distributed RAM replaced "
           "by flip-flops so every path has timing arcs). **No placement and no routing delay**, which "
           "on an FPGA is often half of a path, so these are not clock frequencies and not timing "
           "sign-off; they only compare the cores with each other.", ""]
    for core, title in (("single", "Core A"), ("pipe", "Core B"), ("pipe_fd", "Core B with the FPU")):
        text = (REPO / "build" / "synth" / core / "sta.txt").read_text()
        m = re.search(r"Latest arrival time in '\S+' is (\d+):\n((?:.*\n)*?)(?:\n|$)", text)
        lines = m.group(2).splitlines()
        nets = [l.strip() for l in lines if l.strip().startswith("\\")]
        cells = [re.sub(r"\$[^ ]*\$", "", l.strip()) for l in lines if re.match(r"\s*\d+ ", l)]
        kinds = Counter(re.search(r"\((\w+)\.", c).group(1) for c in cells if re.search(r"\((\w+)\.", c))
        out += [f"## {title}: {int(m.group(1)) / 1000:.1f} ns", "",
                f"Path end: `{nets[0] if nets else '?'}`. Cells on the path: "
                + ", ".join(f"{n} {k}" for k, n in kinds.most_common()) + ".", ""]
    return out


def main():
    if "--timing" in sys.argv:
        print("\n".join(timing()))
        return
    head = ["# Synthesis report (Yosys, Spartan-7 XC7S50)", "",
            "Generated by `make synth` (`synth_xilinx -family xc7`, scripts in `synth/`). "
            "Each core is synthesised on its own with its memory interface as the top-level ports "
            "(core B twice: as RV32IM, and with the FPU parameter set, RV32IMFD); "
            "the commit port and viewer probes are left unconnected, so logic that only feeds "
            "verification is removed. Core A's instruction and data memories are outside the core "
            "(they are combinational reads, which a real single-cycle design would need as "
            "asynchronous RAM); core B's caches are inside and map to block RAM.", ""]
    body, ok = [], True
    tot = {}
    for core, title in (("single", "Core A: single cycle"), ("pipe", "Core B: 5-stage pipeline with caches"),
                        ("pipe_fd", "Core B with the FPU (RV32IMFD)")):
        sec, fits, tot[core] = section(core, title)
        body += sec
        ok &= fits
    a, b = tot["pipe"], tot["pipe_fd"]
    body += ["## What the FPU costs", "",
             "| | Core B | Core B + FPU | Difference |", "|---|---:|---:|---:|"]
    for k, label in (("LUT", "LUTs"), ("FF", "Flip-flops"), ("BRAM36", "Block RAM (36 Kb)"), ("DSP", "DSP48E1")):
        body.append(f"| {label} | {fmt(a[k])} | {fmt(b[k])} | +{fmt(b[k] - a[k])} |")
    body += ["", f"The core with the FPU uses {100 * b['LUT'] / CAPACITY['LUT']:.1f}% of the XC7S50's LUTs and "
                 f"{b['DSP']} of its {CAPACITY['DSP']} DSP blocks (the 53 x 53-bit significand multiplier takes "
                 f"{b['DSP'] - a['DSP']}).  The difference is more than the FPU block itself: the f register "
                 "file, three 64-bit forwarding muxes and the F/D pipeline registers are in the core.", ""]
    tail = ["## What these numbers are not", "",
            "Yosys maps to 7-series cells but does not place, route or time them, and no open-source "
            "flow gives timing sign-off for this part. `make sta` writes a logic-only delay estimate "
            "to [timing.md](timing.md), useful only for comparing the cores. None of them has "
            "been run on a real board."]
    print("\n".join(head + body + tail))
    if "--check" in sys.argv and not ok:
        sys.exit("a design does not fit the XC7S50")


if __name__ == "__main__":
    main()
